---
title: "About me"
output: html_document 
---

## Hello, I'm Alexandra ("Alex")

![ME] (/MADA/picture.JPEG)
 
### **My Background**
 
  I am a second year MPH student, my concentration is in Biostatistics. 
  I always think that the knowledge of the data will give you decision power, 
  that was the main reason that made me take the decision to come back to school after so many years. 
  I am originally from Colombia, I got my bachelor degree as a Food Engineer back in 2011.
  I decided to move to the Unites States in 2015 and just until 2020 in the middle of the 
  COVID-19 Pandemic I started this journey. It amazing how you can find data about so 
  many topics and you can transform it to create big impact over the entire population.
  
### **Experience**
  I work at Gwinnett Health Department as a Health Inspector, 
  I have been working as part of the COVID-19 response team, 
  during the last year and half. My goal is be fully involved in the data analysis for infectious diseases.
  
### **Course Goals**
  Through this MPH journey I have been using STATA, SAS and R. I have some personal preference; however, I really enjoy the facts that you can find tons of good resources about R just using Google. Making our life a little be easy. With MADA I have so many expectations, such as:
    - Improve my data analysis, specifically in infectious diseases.
    - Get familiar with clean data 
    - Process data in R to get usable outcomes
    - Learn about machine learning
  
### **Hobbies and Fun Facts**
  - Deep sea fishing has been a familiar activity that started as a curiosity and now is part of our summers.
    
  - As my first language is Spanish I really enjoy doing activities to improve my English proficiency such as, listen podcast or reading.
  
### **Usable link**
[COVID Data Tracker](https://covid.cdc.gov/covid-data-tracker/#vaccinations_vacc-people-onedose-pop-pop18) Is a very interesting website which shows overall US COVID-19 vaccine. You will find: Deliveries and Administration; Maps, charts, and data provided by CDC,** updates daily by 8 pm ET**
Represents all vaccine partners including jurisdictional partner clinics, retail pharmacies, long-term care facilities, dialysis centers, Federal Emergency Management Agency and Health Resources and Services Administration partner sites, and federal entity facilities.. 


    
  
  
